# Generated by Django 2.2 on 2021-01-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TCompModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardip', models.CharField(max_length=20)),
                ('fsvip', models.CharField(max_length=10)),
                ('dir', models.CharField(max_length=255)),
                ('port', models.SmallIntegerField(null=True)),
            ],
        ),
    ]
