# Generated by Django 2.2 on 2020-09-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalibModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fsvip', models.CharField(max_length=20)),
                ('ip', models.CharField(max_length=20)),
                ('template_path', models.CharField(max_length=255)),
                ('lowtemp', models.SmallIntegerField(null=True)),
                ('normtemp', models.SmallIntegerField(null=True)),
                ('hightemp', models.SmallIntegerField(null=True)),
                ('port', models.SmallIntegerField(null=True)),
                ('period', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpgradeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('armfile_path', models.CharField(blank=True, max_length=255, null=True)),
                ('bbfile_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
